### ISSUE TITLE
Solve scripting: a project creation API

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#87]
I originally argued for scripting hooks at various build stages (see #22). However, this comes with limitations of what those scripts can achieve. [It was suggested](https://github.com/Trick-17/clang-build/issues/22#issuecomment-377929339) to provide function hooks in the target classes etc., but I believe this would be somewhat complicated to implement well and for users to understand and use correctly.

It could be far more powerful to allow simply **running a script instead of using the config file**.

The name of this script could be fixed to `clang-build.py` and would take precedence over any config file, i.e. the first thing `clang-build` would do is look for this script and, if found, run it.
This script could **use the clang-build API** or do whatever to achieve it's goal. As this would be on a per-project basis, the config file-based approach and this new API-based approach could still be used in conjunction.

Note that this would also make the build-stage dependent script keywords of #22 redundant, simplifying the definition of the toml file.
It would further make #54 completely redundant.

**TODO**
- [x] replace the script hooks with one single hook up front
- [x] improve the API
- [x] document the feature
- [x] document the API

API improvements
----------------------------------------------------------------------------

As a user, I would expect to be able to easily create a target, add dependencies to it and call `build` or `compile` and `link`. This might take the following form:

```Python
import os
from clang_build import project, target

# Search for system-installed boost
# ...
if not boost_found:
    print("boost not found!")
    exit(1)
boost = project(name="boost")

# Generate targets for needed boost libraries
filesystem = target(name="filesystem")
boost.add_target(filesystem)
# ...

# Generate some code into "include/mylib" (e.g. version.hpp) and "src" in dependency on an environment "build option"
# ...
if os.environ['build_fast']:
    # ...
else:
    # ...

# Create main target
mylib = target(name="mylib")
mylib.include_directories += boost

# Create main project
project_mylib = project(name="mylib")
project_mylib .add_target(mylib)

# Build
project_mylib.compile()
project_mylib.link()
```

This would enable the following important use cases
----------------------------------------------------------------------------

### Discovery of system-installed libraries

See also #41.
While this would require each project to define its own way of locating its dependencies and creating corresponding targets, it would be a decent solution.

### Generating sources beforehand or at various stages of the build

Generating sources from Python scripts is easy and powerful, allowing things to be done far more easily than in CMake.

### Custom build options

A project can define its own build options, parsing them e.g. from environment variables or a custom configuration file.

**Comment by GPMueller** [comment]
I just realized the obvious drawback of this approach over fixed hooks: **it is not immediately clear how dependent targets should locate the headers and built binaries of a target built with a `clang-build.py` script**.

I believe we really don't want to enable anyone to write a `clang-build` project, which cannot be used as a dependency elsewhere.

The most straightforward solution might be to require a function, named for example `create_project`, to be present in the script and require it to return an instance of the `Project` class. This could then be embedded as a subproject by dependent projects, or as the root project if called directly.

**Comment by GPMueller** [comment]
### Directory-based project creation

This allows for example the creation of sources before the project is created

```python
import clang_build

"""
Sources can be generated and subsequentially a project created
"""

def get_project(directory, environment) -> clang_build.project.Project:
    with open(directory / "main.cpp", "w") as fh:
        fh.write(
            "#include <iostream>\n"
            "\n"
            "int main()\n"
            "{\n"
            "    std::cerr << \"............\\n\";\n"
            "    return 1;\n"
            "}")

    return clang_build.project.Project(directory, environment)
```

-------------------------------------------------

### Target-based project creation

Creating targets by hand would allow for example to use environment variables to determine whether to build with or without OpenMP support, e.g. by adding defines and flags if a certain environment variable is present.

```python
# TODO: write example of using this API
```

-------------------------------------------------

### Derived classes

Deriving e.g. from `Project`, `Target` allows to alter what happens when the `Project` functions are called (currently only `build`, but later maybe `compile`, `link` and others?).

```python
# TODO: write example of using this API
```
